# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88d9ba84d4c4d2b767ae5ede30f55da710a2dd0fe868a6118c2073436ea9d23b1684bd8d882ed92aec67b49967754e2c16faad97e1ec7bf273b07dc365ba9e91

test:
  secret_key_base: 28ca71956eae7bd3a40366d3f0223e03f7ec393b54e046ec1e6edb6fcd3c2e415893566667fa197fd7d2d8ae7d1eb119bed08f501029d118015de0cc85cb733a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
